num1 = 0;
num2 = 0;
$(function(){
    $(window).scroll(function(){
        if($(this).scrollTop() >= '750'){ 
            console.log("NO")
            num2++;
            start1();
        }else{
            console.log("yes")
            num1++;
            start();
        }
    });
});

function start(){
    if(num1 == 1){
        $("#border").animate({
        'left':'10vw'
    },{
        'duration':0
    })
    $("#p1").animate({
        'top':'5vh'
    },{
        'duration':0
    })
    $("#p2").animate({
        'top':'4vh'
    },{
        'duration':0
    })
    $("#border").animate({
        'opacity':1,
        'width':'40vw',
        'left':'-10vw'
    },{
        'duration':2000
    })
    $("#p1").animate({
        'opacity':1,
        'top':0
    },{
        'duration':2000
    })
    $("#p2").animate({
        'opacity':1,
        'top':'7vh'
    },{
        'duration':2000
    })
    setTimeout(start2,2000)
}else{
  
}
}
function start2(){
    setTimeout(()=>{
        $("#d2").animate({
            'left':'90vw'
         },{
           'duration':0
         })
         $("#d3").animate({
            'top':'9vh'
         },{
           'duration':0
         })
        $("#d1").animate({
           'width':'80vw'
        },{
          'duration':2000
        })
        $("#d2").animate({
            'width':'80vw',
            'left':'10vw'
         },{
           'duration':2000
         })
         $("#d3").animate({
            'height':'42vw',
            'top':'-9.5vh'
         },{
           'duration':2000
         })
         $("#d4").animate({
            'height':'42vw'
         },{
           'duration':2000
        })
           setTimeout(()=>{
            $("#d1").animate({
                'width':'0vw',
                'left':'90vw'
             },{
               'duration':2000
             })
             $("#d2").animate({
                 'width':'0vw',
                 'left':'10vw'
              },{
                'duration':2000
              })
              $("#d3").animate({
                 'height':'0vw',
                 'top':'-9.5vh'
              },{
                'duration':2000
              })
              $("#d4").animate({
                 'height':'0vw',
                 'top':'9.5vh'
              },{
                'duration':2000
             })
           })
         },2000)
}
function start1(){

    if(num2 == 1){
        $("#border2").animate({
        'left':'10vw'
    },{
        'duration':0
    })
    $("#p11").animate({
        'top':'5vh'
    },{
        'duration':0
    })
    $("#p22").animate({
        'top':'4vh'
    },{
        'duration':0
    })
    $("#border2").animate({
        'opacity':1,
        'width':'40vw',
        'left':'-10vw'
    },{
        'duration':2000
    })
    $("#p11").animate({
        'opacity':1,
        'top':0
    },{
        'duration':2000
    })
    $("#p22").animate({
        'opacity':1,
        'top':'7vh'
    },{
        'duration':2000
    })
    setTimeout(start22,2000)
}else{
  
}
}
function start22(){
    setTimeout(()=>{
        $("#d22").animate({
            'left':'90vw'
         },{
           'duration':0
         })
         $("#d33").animate({
            'top':'9vh'
         },{
           'duration':0
         })
        $("#d11").animate({
           'width':'80vw'
        },{
          'duration':2000
        })
        $("#d22").animate({
            'width':'80vw',
            'left':'10vw'
         },{
           'duration':2000
         })
         $("#d33").animate({
            'height':'42vw',
            'top':'-9.5vh'
         },{
           'duration':2000
         })
         $("#d44").animate({
            'height':'42vw'
         },{
           'duration':2000
        })
           setTimeout(()=>{
            $("#d11").animate({
                'width':'0vw',
                'left':'90vw'
             },{
               'duration':2000
             })
             $("#d22").animate({
                 'width':'0vw',
                 'left':'10vw'
              },{
                'duration':2000
              })
              $("#d33").animate({
                 'height':'0vw',
                 'top':'-9.5vh'
              },{
                'duration':2000
              })
              $("#d44").animate({
                 'height':'0vw',
                 'top':'9.5vh'
              },{
                'duration':2000
             })
           })
         },2000)
}

